steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f','couchbase-cluster.yaml']
options:
  env: 
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=couchbase-cluster'