steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['./enable-google-services.sh']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['cluster-info']
options:
  env: 
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=couchbase-cluster'